name: Deploy release candidate

on:
  push:
    branches:
      - "release/*"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
      concurrency_group: dev
      staging_branch: ${{ github.ref_name }}
