name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
      concurrency_group: production
